### ISSUE TITLE
There is a memory leak problem, when broadcasting ICE::Proxy with DataStorm.

### ISSUE THREAD

**Issue by zengdaiwei** [zeroc-ice/datastorm#12]
There is a memory leak problem, when broadcasting ICE::Proxy with DataStorm.
I have already created an issue for zeroc-ice: zeroc-ice/datastorm#13
As I am not sure if the problem is directly caused by ice or datastorm,  so may you bother to have a look at it when you are enjoying free leisure moments.

**Comment by bentoi** [comment]
Dup of #13
