### ISSUE TITLE
steady memory leaks with ICE when broadcasting proxy with DataStorm

### ISSUE THREAD

**Issue by zengdaiwei** [zeroc-ice/datastorm#13]
**Version(please complete the following information):**
 - Ice Version 3.7.6
 - OS: Windows
 - Distribution: nuget

**Describe the bug**
1, create a Proxy with DataStorm::Node's communicator, then broadcast the proxy. 
2, If the proxy is not received by any Client, try to destroy it. 
3, repeat step 1、2
4, obvious memory leak shown in VS analyzer; 

here is my demo project to show the bug:
https://github.com/zengdaiwei/ICEMemoryLeak.git
run with visual studio 2019, compile and run; just keep "Enter" key down for a minutes or so, to reproduce the problem.

**Expected behavior**
no steady memory leaks with "creating proxy"--"broadcasting proxy"--"destroy proxy" loops.

**Additional context**
test projects to reproduce the bug: https://github.com/zengdaiwei/ICEMemoryLeak.git

**Comment by bentoi** [comment]
You don't indicate if you're using DataStorm 1.0 or the GitHub latest version. If you're using 1.0, can you try to build DataStorm from the GitHub repository and see if this fixes the problem?

**Comment by zengdaiwei** [comment]
I used nuget from https://nuget.cdn.azure, which has only DataStorm 1.0.0; 
As you suggested,  I compiled the latest-version DataStorm GitHub, and tried it with the  test project "https://github.com/zengdaiwei/ICEMemoryLeak.git" again. The leaking problem still exists. I am sure the latest DataStorm code is used.
Please have a look at the test code and take a little time to try it out.

**Comment by bentoi** [comment]
Sorry for the late feedback on this one. There's a leak in your test case, you should call `adapter->destroy()` instead of just `adapter->deactivate()`. Can you try again with this fix?

**Comment by zengdaiwei** [comment]
It works. Thanks.
